11 create a errors flag on the investment entity it must be null or error type when there is an error on entity construction
henrfarias/arkad-api pull request #12
Opened 2022-05-14 22:03 UTC by henrfarias

Create an error interface.
It implements an error on the entity constructor if there is one.

2022-05-21 00:42 UTC, jhonpedro commented on src/domain/errors/investment-errors.ts
> +export class InvestmentErrors {
A question here. Wouldn't that class here need to extend a `Error` class too? 

I'm sure why but know that it helps the runtime to more descritive errors, and I heard that it's a good practice to do it. But I can't explain it to you why I'll search why.

2022-05-21 14:11 UTC, henrfarias commented on src/domain/errors/investment-errors.ts
> +export class InvestmentErrors {
Interesting. 

I will search more about that. Anyway, I will implement this extension.

2022-05-21 14:54 UTC, henrfarias commented
As we have talked about, I create a base error "Bad Request", this error can be extended to create another more specific error. So, I move it to path errors>base-errors>bad-request.ts. In the future, when we need it, we will be able to create a folder "specific-errors" to extend the base errors. What do you think?

2022-05-28 17:48 UTC, jhonpedro requested changes

2022-05-28 17:48 UTC, jhonpedro commented on src/domain/entity/investment.ts
> +  readonly error: Error | null
This variable `error` here have a type as a common `Error`, because of that we don't know the values inside it if we store any there. We need to create an Error class pattern so that the application know what's is inside this new error variable.

2022-05-29 20:32 UTC, henrfarias commented
So, I created a custom error with that name to have some differences from the other projects.

2022-06-11 01:43 UTC, jhonpedro approved these changes
Nice work!

2022-06-11 01:44 UTC, jhonpedro commented
I always look at the code, approve it and forgot to see if there is any conflicts. Can you take a look at them please?

2022-06-13 12:03 UTC, merged